kind: pipeline
type: docker
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: steverobertson/zxplay
      tags: ["latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
