kind: pipeline
type: docker
name: default

platform:
  arch: amd64
  os: linux

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: steverobertson/zxplay
      tags: ["latest"]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

trigger:
  branch:
    - main
